tasks:
  - init: |
      echo 'TODO: build project'
    command: |
      export apiadd="https://8080-${GITPOD_WORKSPACE_URL##https://}" && docker-compose up
ports:
  - port: 8080
    visibility: public


