tasks:
  - init: |
      echo 'TODO: build project'
    command: |
      export HOST="https://9966-${GITPOD_WORKSPACE_URL##https://}" && export apiadd="https://8080-${GITPOD_WORKSPACE_URL##https://}/" && docker-compose up

